version: "3"
services: 
  influxdb:
    image: influxdb
    container_name: influxdb_pr
    ports:
      - "8086:8086"        
    volumes:
      - /home/adrian/volumes/influxdb-data:/var/lib/influxdb2
 
  grafana:
    image: grafana/grafana
    container_name: grafana_pr
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  
  node-red:
    image: nodered/node-red
    container_name: node-red_pr
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
  
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_pr
    environment:
      - TZ=America/Mexico_City    
    volumes:
      - /home/adrian/volumes/mosquitto/config:/mosquitto/config
      - /home/adrian/volumes/mosquitto/data:/mosquitto/data
      - /home/adrian/volumes/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
volumes:
  grafana-storage: {}
  node-red-data: